#!/usr/bin/env bash
# .claude/hooks/pre-compact.sh
# Fires BEFORE Claude compacts the context window.
# Updates session_handover.md, CLAUDE.md, and README so nothing is lost.
# Input: JSON on stdin with compaction trigger context

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
STATE_FILE="$PROJECT_DIR/.claude/session/state.json"
HANDOVER_FILE="$PROJECT_DIR/session_handover.md"
AUDIT_LOG="$PROJECT_DIR/.claude/compact-audit.log"

log() { echo "[pre-compact] $*" >&2; }

log "PreCompact triggered at $TIMESTAMP"

# ── Read compaction context from stdin ──────────────────────────────────────
INPUT=$(cat)
TRIGGER=$(echo "$INPUT" | jq -r '.trigger // "auto"' 2>/dev/null || echo "auto")
CONTEXT_PCT=$(echo "$INPUT" | jq -r '.context_percent // "unknown"' 2>/dev/null || echo "unknown")

log "Trigger: $TRIGGER | Context: $CONTEXT_PCT%"

# ── Ensure session state directory exists ───────────────────────────────────
mkdir -p "$PROJECT_DIR/.claude/session"

# ── Capture git context ──────────────────────────────────────────────────────
GIT_BRANCH=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git -C "$PROJECT_DIR" log --oneline -1 2>/dev/null || echo "none")
GIT_STATUS=$(git -C "$PROJECT_DIR" status --short 2>/dev/null | head -10 || echo "")
MODIFIED_FILES=$(git -C "$PROJECT_DIR" diff --name-only 2>/dev/null | head -10 || echo "")

# ── Update session state JSON ────────────────────────────────────────────────
if [ -f "$STATE_FILE" ]; then
  PREV_STATE=$(cat "$STATE_FILE")
  ACTIVE_TASK=$(echo "$PREV_STATE" | jq -r '.active_task // "unknown"' 2>/dev/null || echo "unknown")
  PHASE=$(echo "$PREV_STATE" | jq -r '.phase // "unknown"' 2>/dev/null || echo "unknown")
  NEXT_ACTION=$(echo "$PREV_STATE" | jq -r '.next_action // "unknown"' 2>/dev/null || echo "unknown")
else
  ACTIVE_TASK="unknown"
  PHASE="unknown"
  NEXT_ACTION="unknown"
fi

cat > "$STATE_FILE" <<EOF
{
  "last_updated": "$TIMESTAMP",
  "trigger": "$TRIGGER",
  "context_pct_at_compact": "$CONTEXT_PCT",
  "git_branch": "$GIT_BRANCH",
  "git_last_commit": "$GIT_COMMIT",
  "active_task": "$ACTIVE_TASK",
  "phase": "$PHASE",
  "next_action": "$NEXT_ACTION",
  "modified_files": $(echo "$MODIFIED_FILES" | jq -R -s 'split("\n") | map(select(. != ""))' 2>/dev/null || echo "[]"),
  "compact_count": $(cat "$STATE_FILE" 2>/dev/null | jq -r '.compact_count // 0' | awk '{print $1+1}' 2>/dev/null || echo 1)
}
EOF

# ── Generate/update session_handover.md ─────────────────────────────────────
python3 "$PROJECT_DIR/scripts/generate_session_handover.py" \
  --trigger "$TRIGGER" \
  --context-pct "$CONTEXT_PCT" \
  --branch "$GIT_BRANCH" \
  --commit "$GIT_COMMIT" \
  2>/dev/null || {
    # Fallback: write minimal handover if Python fails
    cat > "$HANDOVER_FILE" <<HANDOVER
# Session Handover
_Auto-generated by pre-compact hook at $TIMESTAMP_

## Context snapshot
- **Trigger**: $TRIGGER
- **Context at compact**: $CONTEXT_PCT%
- **Branch**: $GIT_BRANCH
- **Last commit**: $GIT_COMMIT

## Active task
$ACTIVE_TASK

## Next action
$NEXT_ACTION

## Modified files
$MODIFIED_FILES

## Notes
Context was compacted. Check git log for work completed this session.
HANDOVER
    log "Python script failed — wrote minimal handover"
}

# ── Update CLAUDE.md active work context section ─────────────────────────────
python3 "$PROJECT_DIR/scripts/update_context_files.py" \
  --mode compact \
  --timestamp "$TIMESTAMP" \
  --branch "$GIT_BRANCH" \
  --task "$ACTIVE_TASK" \
  --phase "$PHASE" \
  --next-action "$NEXT_ACTION" \
  2>/dev/null || log "update_context_files.py skipped (not blocking)"

# ── Append to audit log ──────────────────────────────────────────────────────
echo "{\"timestamp\":\"$TIMESTAMP\",\"trigger\":\"$TRIGGER\",\"context_pct\":\"$CONTEXT_PCT\",\"branch\":\"$GIT_BRANCH\"}" \
  >> "$AUDIT_LOG" 2>/dev/null || true

# ── Emit context injection text for Claude ───────────────────────────────────
# Anything echoed to stdout is injected into Claude's context post-compaction
cat <<INJECT
=== COMPACTION CONTEXT PRESERVED ===
Timestamp: $TIMESTAMP
Branch: $GIT_BRANCH
Last commit: $GIT_COMMIT
Active task: $ACTIVE_TASK
Phase: $PHASE
Next action: $NEXT_ACTION

session_handover.md has been updated with full task state.
Read session_handover.md to restore full context.
Type /token-status to see current usage after compaction.
=== END CONTEXT INJECTION ===
INJECT

log "PreCompact complete"
exit 0
