#!/usr/bin/env bash
# .claude/hooks/pre-compact.sh
# Fires BEFORE Claude compacts the context window.
# Saves all session state to disk and git so nothing is lost.
# Input: JSON on stdin with compaction trigger context

set -euo pipefail
umask 0077

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
# shellcheck source=../../scripts/find_python.sh
source "${CLAUDE_PLUGIN_ROOT:-$PROJECT_DIR}/scripts/find_python.sh"
# Python is preferred but optional — if absent we degrade to a heredoc-based
# fallback handover rather than blocking the compaction (exit 2 would wedge
# the session at high context for any user without python3).
PYTHON_OK=true
if ! "$PYTHON" -c "import sys; sys.exit(0)" 2>/dev/null; then
  echo "[pre-compact] WARNING: Python 3 not found — using fallback handover (limited fidelity)" >&2
  PYTHON_OK=false
fi
# shellcheck source=../../scripts/resolve_state_dir.sh
source "${CLAUDE_PLUGIN_ROOT:-$PROJECT_DIR}/scripts/resolve_state_dir.sh"

# Collapse a double fire (plugin + opened repo) so compact_count isn't double
# incremented and we don't write two snapshot commits for one compaction.
hook_once pre-compact || exit 0

# Handover lives at MAIN_ROOT under auto/main scope so it survives worktree
# deletion. Under scope=local it stays in the worktree by design.
case "$STATE_SCOPE" in
  local) HANDOVER_DIR="$REPO_ROOT" ;;
  *)     HANDOVER_DIR="$MAIN_ROOT" ;;
esac
HANDOVER_FILE="$HANDOVER_DIR/session_handover.md"
AUDIT_LOG="$MAIN_ROOT/.claude/compact-audit.log"

log() { echo "[pre-compact] $*" >&2; }

log "PreCompact triggered at $TIMESTAMP"

# ── Read compaction context from stdin ──────────────────────────────────────
INPUT=$(cat)
TRIGGER=$(echo "$INPUT" | jq -r '.trigger // "auto"' 2>/dev/null || echo "auto")
CONTEXT_PCT=$(echo "$INPUT" | jq -r '.context_percent // "unknown"' 2>/dev/null || echo "unknown")

log "Trigger: $TRIGGER | Context: $CONTEXT_PCT%"

# ── Ensure state directory exists (resolve_state_dir.sh already did this for
#    $STATE_DIR, but in worktree+auto mode the worktree's own dir may also be
#    referenced by other code paths — guarantee it). ──────────────────────────
mkdir -p "$STATE_DIR"

# ── Capture git context ──────────────────────────────────────────────────────
GIT_BRANCH=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git -C "$PROJECT_DIR" log --oneline -1 2>/dev/null || echo "none")
MODIFIED_FILES=$({ git -C "$PROJECT_DIR" diff --name-only 2>/dev/null || true; } | head -10)

# ── Update session state JSON — MERGE with existing, never replace ───────────
# Preserves session_start_time, last_tool_failure, saved_by, and all other
# fields written by other hooks. Only updates compaction-specific fields.
# compact_count is incremented inside the filter so it stays correct even if
# another writer touches state.json concurrently (lock-guarded).
MODIFIED_FILES_JSON=$(echo "$MODIFIED_FILES" | jq -R -s 'split("\n") | map(select(. != ""))' 2>/dev/null || echo "[]")

state_write \
  '.last_updated           = $ts
   | .trigger                = $trigger
   | .context_pct_at_compact = $ctx
   | .git_branch             = $branch
   | .git_last_commit        = $commit
   | .modified_files         = $files
   | .compact_count          = ((.compact_count // 0) + 1)
   | .active_task            = (.active_task // "unknown")
   | .phase                  = (.phase // "unknown")
   | .next_action            = (.next_action // "read session_handover.md")' \
  --arg ts        "$TIMESTAMP" \
  --arg trigger   "$TRIGGER" \
  --arg ctx       "$CONTEXT_PCT" \
  --arg branch    "$GIT_BRANCH" \
  --arg commit    "$GIT_COMMIT" \
  --argjson files "$MODIFIED_FILES_JSON" \
  || log "WARNING: state.json update failed"

# Re-read merged state for handover generation
COMPACT_COUNT=$(jq -r '.compact_count // 1' "$STATE_FILE" 2>/dev/null || echo "1")
ACTIVE_TASK=$(jq -r '.active_task // "unknown"' "$STATE_FILE" 2>/dev/null || echo "unknown")
PHASE=$(jq -r '.phase // "unknown"'             "$STATE_FILE" 2>/dev/null || echo "unknown")
NEXT_ACTION=$(jq -r '.next_action // "unknown"' "$STATE_FILE" 2>/dev/null || echo "unknown")

# ── Generate/update session_handover.md ─────────────────────────────────────
log "Generating session_handover.md -> $HANDOVER_FILE"
_HANDOVER_OK=false
if [ "$PYTHON_OK" = true ]; then
  if "$PYTHON" "$PROJECT_DIR/scripts/generate_session_handover.py" \
       --trigger "$TRIGGER" \
       --context-pct "$CONTEXT_PCT" \
       --branch "$GIT_BRANCH" \
       --commit "$GIT_COMMIT" \
       --output "$HANDOVER_FILE" \
       2>&1 | while IFS= read -r line; do log "$line"; done; then
    _HANDOVER_OK=true
  else
    log "WARNING: generate_session_handover.py failed — falling back to heredoc"
  fi
fi
if [ "$_HANDOVER_OK" != true ]; then
  cat > "$HANDOVER_FILE" <<HANDOVER
# Session Handover
_Auto-generated by pre-compact hook at ${TIMESTAMP}_

## Context snapshot
- **Trigger**: $TRIGGER
- **Context at compact**: $CONTEXT_PCT%
- **Branch**: $GIT_BRANCH
- **Last commit**: $GIT_COMMIT

## Active task
$ACTIVE_TASK

## Next action
$NEXT_ACTION

## Modified files
$MODIFIED_FILES

## Notes
Context was compacted. Check git log for work completed this session.
HANDOVER
fi

# ── Update CLAUDE.md active work context section ─────────────────────────────
if [ "$PYTHON_OK" = true ]; then
  "$PYTHON" "$PROJECT_DIR/scripts/update_context_files.py" \
    --mode compact \
    --timestamp "$TIMESTAMP" \
    --branch "$GIT_BRANCH" \
    --task "$ACTIVE_TASK" \
    --phase "$PHASE" \
    --next-action "$NEXT_ACTION" \
    2>&1 | while IFS= read -r line; do log "$line"; done || true
fi

# ── Commit session files to git so session-sync can push them ────────────────
# Uses --no-verify: hooks already ran; this is a mechanical snapshot commit.
# Commit from MAIN_ROOT because under worktree+auto scope state.json and the
# handover live there. CLAUDE.md is added from whichever root owns it.
log "Committing session snapshot to git (cwd=$MAIN_ROOT)..."
(
  cd "$MAIN_ROOT" || exit 0
  # Stage files relative to MAIN_ROOT — git add ignores missing paths under || true.
  git add .claude/session/state.json \
          .claude/session/turn-ledger.jsonl \
          .claude/session/tool-failures.jsonl \
          session_handover.md \
          CLAUDE.md \
          2>/dev/null || true
  # If we're in a worktree under auto scope and the worktree itself has fresher
  # CLAUDE.md / session_handover.md edits, sync them to MAIN_ROOT now so they
  # land in this snapshot rather than waiting for SessionEnd.
  if [ "$IN_WORKTREE" = true ] && [ "$STATE_SCOPE" != "local" ]; then
    if [ -f "$PROJECT_DIR/CLAUDE.md" ] && [ "$PROJECT_DIR/CLAUDE.md" -nt "$MAIN_ROOT/CLAUDE.md" ]; then
      cp "$PROJECT_DIR/CLAUDE.md" "$MAIN_ROOT/CLAUDE.md" 2>/dev/null \
        && git add CLAUDE.md 2>/dev/null || true
    fi
  fi
  if git diff --cached --quiet 2>/dev/null; then
    log "No changes to commit (files unchanged)"
  else
    git commit --no-verify -m "chore(context): pre-compact snapshot [$TIMESTAMP] ctx=${CONTEXT_PCT}%" \
      2>&1 | while IFS= read -r line; do log "$line"; done \
    || log "WARNING: git commit failed (not blocking)"
  fi
) || true

# ── Append to audit log ──────────────────────────────────────────────────────
jq -nc \
  --arg ts      "$TIMESTAMP" \
  --arg trigger "$TRIGGER" \
  --arg ctx     "$CONTEXT_PCT" \
  --arg branch  "$GIT_BRANCH" \
  --argjson count "$COMPACT_COUNT" \
  '{timestamp: $ts, trigger: $trigger, context_pct: $ctx, branch: $branch, compact_count: $count}' \
  >> "$AUDIT_LOG" 2>/dev/null || true

# ── Emit context injection text for Claude ───────────────────────────────────
# Stdout is injected into Claude's context window after compaction
cat <<INJECT
=== COMPACTION CONTEXT PRESERVED ===
Timestamp  : $TIMESTAMP
Branch     : $GIT_BRANCH
Last commit: $GIT_COMMIT
Active task: $ACTIVE_TASK
Phase      : $PHASE
Next action: $NEXT_ACTION
Compactions: $COMPACT_COUNT

session_handover.md has been updated and committed.
Read session_handover.md to restore full task context.
Type /token-status to see usage after compaction.
=== END CONTEXT INJECTION ===
INJECT

log "PreCompact complete (compact #$COMPACT_COUNT)"
exit 0
